---
- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Restart cron
  ansible.builtin.systemd:
    name: cron
    state: restarted

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart ssh socket
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted
    daemon_reload: true

- name: Restart smartd
  ansible.builtin.systemd:
    name: smartmontools
    state: restarted
