---
- name: Установить пакет locales
  ansible.builtin.apt:
    name: locales
    state: present

- name: Сгенерировать локали
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ common_locales }}"

- name: Задать локаль по умолчанию
  ansible.builtin.copy:
    content: "LANG={{ common_default_locale }}\n"
    dest: /etc/default/locale
    owner: root
    group: root
    mode: "0644"
