---
- name: Установить msmtp в качестве MTA
  ansible.builtin.apt:
    name:
      - msmtp
      - msmtp-mta
      - mailutils
    state: present

- name: Разложить конфигурацию msmtp
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: mail
    mode: "0640"
  no_log: true

- name: Направить почту root на адрес дежурной службы
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: '^root:'
    line: "root: {{ common_mail_to }}"
    create: true
    owner: root
    group: root
    mode: "0644"
