---
- name: Разложить конфигурацию smartd
  ansible.builtin.template:
    src: smartd.conf.j2
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart smartd

- name: Включить проверку дисков по расписанию
  ansible.builtin.systemd:
    name: smartmontools
    enabled: true
    state: started
  failed_when: false
